export enum TaskEvent {
  TASK_STARTED = 'TASK_STARTED',
  TASK_PROGRESS = 'TASK_PROGRESS',
  TASK_COMPLETED = 'TASK_COMPLETED',
  TASK_FAILED = 'TASK_FAILED',
  TASK_ABORTED = 'TASK_ABORTED',
  TASK_EXPIRED = 'TASK_EXPIRED',
  TASK_PAUSED = 'TASK_PAUSED',
  TASK_ARCHIVED = 'TASK_ARCHIVED',
}
