export enum WebhookEvent {
  TASK_STARTED = 'TASK_STARTED',
  TASK_COMPLETED = 'TASK_COMPLETED',
  TASK_FAILED = 'TASK_FAILED',
  TASK_ABORTED = 'TASK_ABORTED',
  TASK_EXPIRED = 'TASK_EXPIRED',
  TASK_CLEANED = 'TASK_CLEANED',
  TASK_PAUSED = 'TASK_PAUSED',
  TASK_ARCHIVED = 'TASK_ARCHIVED',
}
